### ISSUE TITLE
This doesn't appear to actually work

### ISSUE THREAD

**Issue by lucqui** [trajano/reverse-proxy-auth-sonar-plugin#1]
I've tried it with some injected headers and I'm not actually seeing any user creation or the like...

**Comment by trajano** [comment]
Can you provide a bit more details such as what header you are using and what settings you have done. 

Also an fyi I haven't tested on v5 of sonar as my environment has not been updated to v5

**Comment by lucqui** [comment]
Of course.

So I have tested it both in version 5 and in version 4.5.2 of sonarqube and in both cases I appear to get about the same problem.

I'm using the out-of-box settings for sonar with one modification: I attached a debugger. I am using the embedded databases, because I'm just testing a couple things and don't think it is necessary to a jdbc connection. 

I am leaving the default header name (X-Forwarded-User) and setting it to both existing and non-existing users. Users are neither created nor logged in automatically, unfortunately.

**Comment by trajano** [comment]
Seems normal. Are you using local host. That may be the difference.

**Comment by lucqui** [comment]
Yes, I am. This is the default. Should I be expecting this behavior?

Lucas Earl
801.318.4821
earl.lucas@gmail.com
http://www.linkedin.com/in/lucasearl

**Comment by trajano** [comment]
It's the default for the assumption that Jenkins would be on the same server and making calls to sonar.  Try to change it to something else for now.

**Comment by lucqui** [comment]
I guess I didn't catch that part. So this plugin is assumed to be running with an instance of Jenkins?

**Comment by trajano** [comment]
No the Jenkins support was after the fact when I realized I cannot connect to the server using client side certificates. But you should be able to do your testing by changing local host to something else. 

Also I presume you put in the additional properties to enable using the plugin as an alternate realm in sonar properties.

**Comment by lucqui** [comment]
Ok. I see! 

I was actually unaware of this additional property to enable an alternate security realm. Can you suggest me how to do such a thing? Do you know of documentation that I could see? Thanks

**Comment by trajano** [comment]
I remember it was in the documentation somewhere. But I will create a patch later to add it to the readme or site later based on my configuration.

**Comment by lucqui** [comment]
I would really appreciate that.

**Comment by trajano** [comment]
I added the following document

https://github.com/trajano/reverse-proxy-auth-sonar-plugin/blob/master/src/site/markdown/installation.md.vm

Let me know if it works so we can close this off.

**Comment by lucqui** [comment]
Thanks! Works great.
