### ISSUE TITLE
SonarQube 6.0

### ISSUE THREAD

**Issue by ghost** [trajano/reverse-proxy-auth-sonar-plugin#4]
Hi,

is this working for SonarQube 6.0? I couldn't make it authenticate, Sonar throws me 404.

Any ideas?

**Comment by trajano** [comment]
They may have changed the API from what I saw on the logs.

**Comment by ghost** [comment]
Yeah, plugins is crashing on 6.0 due API changes, latest working version is 5.6

**Comment by trajano** [comment]
I'm just checking the last bit which is the ROR override which isn't a documented API that I used to automatically login.

**Comment by trajano** [comment]
Mostly done now, Sonar itself is just complaining on a few things with the code, I'm trying to remedy it before I make a final release.  But if you're in a rush feel free to grab the code and build.  Still working on the autodeploy issue for now.

**Comment by trajano** [comment]
https://jira.sonarsource.com/browse/SONAR-5430 will eventually remove the need of this plugin hopefully.
