### ISSUE TITLE
Could it be that "sonar.web.context" is not supported

### ISSUE THREAD

**Issue by tallandtree** [trajano/reverse-proxy-auth-sonar-plugin#8]
Hi,
I was just looking for this plugin! It looks great! 

But could it be that "sonar.web.context" in sonar.properties is not supported. If I have it set to e.g. /sonarqube, the sonarqube url becomes: http://myserver.domain.net/sonarqube. If I use the reverse proxy, it says: http://myserver.domain.net/sessions/init/reverseproxyauth is not found. If I manually change this to:
http://myserver.domain.net/sonarqube/sessions/init/reverseproxyauth, I'm eventually logged in.

**Comment by rorueda** [comment]
It will work if you set the **Server base URL** under **Configuration > General Settings > General**.

**Comment by trajano** [comment]
Thanks for answering @rorueda I didn't see the notification for this until just now.
